-- ═══════════════════════════════════════════════════════
-- SEED DATA: 40 Bakery Products
-- ═══════════════════════════════════════════════════════

INSERT INTO public.products (name, display_order, active_status) VALUES
  ('White Bread Loaf', 1, true),
  ('Wholemeal Bread Loaf', 2, true),
  ('Multigrain Bread Loaf', 3, true),
  ('Sourdough Loaf', 4, true),
  ('Rye Bread Loaf', 5, true),
  ('Turkish Bread', 6, true),
  ('Pita Bread (Pack of 6)', 7, true),
  ('Lebanese Bread (Pack of 5)', 8, true),
  ('Dinner Rolls (Pack of 12)', 9, true),
  ('Burger Buns (Pack of 6)', 10, true),
  ('Hot Dog Rolls (Pack of 6)', 11, true),
  ('Ciabatta Loaf', 12, true),
  ('Focaccia', 13, true),
  ('Baguette', 14, true),
  ('Garlic Bread', 15, true),
  ('Croissant', 16, true),
  ('Pain au Chocolat', 17, true),
  ('Danish Pastry', 18, true),
  ('Cinnamon Scroll', 19, true),
  ('Fruit Muffin', 20, true),
  ('Chocolate Muffin', 21, true),
  ('Blueberry Muffin', 22, true),
  ('Banana Bread Slice', 23, true),
  ('Scone (Plain)', 24, true),
  ('Scone (Date)', 25, true),
  ('Meat Pie', 26, true),
  ('Sausage Roll', 27, true),
  ('Spinach & Ricotta Roll', 28, true),
  ('Chicken Pie', 29, true),
  ('Beef Pasty', 30, true),
  ('Quiche Lorraine', 31, true),
  ('Lamington', 32, true),
  ('Vanilla Slice', 33, true),
  ('Custard Tart', 34, true),
  ('Apple Turnover', 35, true),
  ('Cheese & Bacon Roll', 36, true),
  ('Vegemite Scroll', 37, true),
  ('Pizza Base (Large)', 38, true),
  ('Gluten-Free Bread Loaf', 39, true),
  ('Sourdough Rolls (Pack of 6)', 40, true)
ON CONFLICT DO NOTHING;
